name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron:  '0 4 * * *'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      expected_version: Release 8.4 (July 2022)
      
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: sudo wget https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip; sudo unzip pup_v0.4.0_linux_amd64.zip -d /usr/local/bin 
      - name: Debug
        run: curl -s https://www.cancerrxgene.org/news | pup 'b text{}' | head -n 1 | cat
      - name: Get Version
        run: curl -s https://www.cancerrxgene.org/news | pup 'b text{}' | head -n 1 >> version.txt; echo "version=$(cat version.txt)" >> $GITHUB_ENV        
      - name: Run Check
        if: ${{ env.version != env.expected_version }}
        run: exit 1
        
      # This command should should work locally
      #- name: Run Check (Ignore) 
      #  run: curl -s https://www.cancerrxgene.org/news | pup 'b text{}' | head -n 1 #| read input && [ "$input" = "Release 8.4 (July 2022)" ] && echo "OK" || exit 1
      

